Add bookings
Abrielz1/java-shareit pull request #3
Opened 2023-02-01 10:38 UTC by Abrielz1

2023-02-02 08:30 UTC, AnastasiyaFomkina requested changes
В `application.properties` нужно удалить `todo` и пересесть на новую базу [PostgresSql](https://javarush.com/groups/posts/2579-dobavljaem-bd-k-restful-servisu-na-spring-boot-chastjh-1)

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (itemDto.getName() != null) item.setName(itemDto.getName());
Нужно вынести блок после условия в скобочки

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (itemDto.getDescription() != null) item.setDescription(itemDto.getDescription());
Нужно вынести блок после условия в скобочки

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            if (itemDto.getAvailable() != null) item.setAvailable(itemDto.getAvailable());
Нужно вынести блок после условия в скобочки

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +        if (text.isBlank()) return Collections.emptyList();
Нужно вынести блок после условия в скобочки

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on pom.xml
> +			<groupId>org.hibernate</groupId>
Лишняя зависимость

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    public BookingDtoResponse create(@RequestHeader("X-Sharer-User-Id") long id, @Validated(Create.class) @RequestBody BookingDto bookingDto) {
Нужно вынести в отдельный класс, например, `Variables` и сделать `public` константой, чтобы использовать и в других контроллерах

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (!item.getAvailable()) throw new BadRequestException("Item not available now for booking");
Нужно вынести блок после условия в скобочки

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +        if (userId != item.getOwner().getId()) throw new ObjectNotFoundException("You can't confirm this booking");
Нужно вынести блок после условия в скобочки

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new BadRequestException("You can't change status after approving");
Нужно вынести блок после условия в скобочки

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public class BookingMapper {
_Саморазвитие_
Все еще предлагаю попробовать для маппинга библиотеку [Mapstruct](https://www.baeldung.com/mapstruct). Она поможет избавить от шаблонного кода

2023-02-02 08:30 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingDtoResponse> getByOwner(long userId, String state) throws UnsupportedStateException;
Пробрасывать выше по стеку `UnsupportedStateException` не нужно, так как данное исключение является **непроверяемым** (наследуется от `RuntimeException`)

2023-02-02 11:35 UTC, Abrielz1 commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
> +public class BookingMapper {
пробовал, не работает, если можно отложу, до последнего спринта

2023-02-03 05:20 UTC, AnastasiyaFomkina requested changes

2023-02-03 05:20 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +    List<BookingDtoResponse> getByOwner(long userId, String state) throws UnsupportedStateException;
Нужно удалить, на тесты никак не влияет

2023-02-03 05:22 UTC, AnastasiyaFomkina commented
В `application.properties` нужно удалить `todo` и пересесть на новую базу [PostgresSql](https://javarush.com/groups/posts/2579-dobavljaem-bd-k-restful-servisu-na-spring-boot-chastjh-1) 

Этот пункт тоже не выполнен, нужно доделать

2023-02-03 14:21 UTC, AnastasiyaFomkina approved these changes

2023-02-03 14:25 UTC, merged