Add item requests
Abrielz1/java-shareit pull request #4
Opened 2023-02-13 00:16 UTC by Abrielz1

2023-02-13 12:40 UTC, AnastasiyaFomkina requested changes
Привет! Отличная работа 🔥 Оставила совсем немного комментариев

2023-02-13 12:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                        @Positive @RequestParam(defaultValue = "20", required = false) int size) {
Можно сразу ожидать от клиента `Pageable pageable`, так не придется настраивать основные поля для пагинации и добавлять новые, если потребуется

2023-02-13 12:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/storage/BookingRepository.java
> +    List<Booking> findAllByBookerIdOrderByStartDesc(long userId, Pageable p);
Переименуй все однобуквенные переменные

2023-02-13 12:40 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/booking/storage/BookingRepositoryTest.java
> +    BookingRepository bookingRepository;
Не хватает модификатора доступа

2023-02-13 12:40 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/item/storage/ItemRepositoryTest.java
> +class ItemRepositoryTest {
Нужно дописать тест

2023-02-13 12:40 UTC, AnastasiyaFomkina commented on src/test/java/ru/practicum/shareit/request/service/ItemRequestServiceImplTest.java
> +    UserRepository userRepository;
Не хватает модификаторов доступа у полей

2023-02-13 12:40 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapper.java
> +public class ItemRequestMapper {
Все еще предлагаю попробовать [mapstruct](https://javarush.com/groups/posts/3698-chto-takoe-mapstruct-i-kak-praviljhno-nastroitjh-ego-dlja-moduljhnogo-testirovanija-v-springboo)

2023-02-13 13:00 UTC, Abrielz1 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                        @Positive @RequestParam(defaultValue = "20", required = false) int size) {
Это надо менять? Если да, то, что надо сделать?

2023-02-13 13:02 UTC, Abrielz1 commented on src/test/java/ru/practicum/shareit/item/storage/ItemRepositoryTest.java
> +class ItemRepositoryTest {
у меня 2 версии тестов для этого класса, он работают, но, когда идет покрытие валятся.

2023-02-13 13:02 UTC, Abrielz1 commented on src/main/java/ru/practicum/shareit/request/mapper/ItemRequestMapper.java
> +public class ItemRequestMapper {
если можно, то я пока откажусь, в пачке видел, как у людей из-а мап стракта всё валится

2023-02-13 13:45 UTC, Abrielz1 commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +                                        @Positive @RequestParam(defaultValue = "20", required = false) int size) {
Попробовал, решил если можно оставлю так, иначе придётся пол-работы переделывать.

2023-02-14 11:46 UTC, AnastasiyaFomkina requested changes

2023-02-14 11:46 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                books.addAll(bookingRepository.findAllByBookerIdOrderByStartDesc(userId, pg));
Сокращения тоже не подойдут. Названия переменных должны быть осмысленными. Нужно изменить

2023-02-14 15:14 UTC, AnastasiyaFomkina approved these changes

2023-02-14 18:15 UTC, merged